// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(c,g,h,k,l){function F(){function a(b,c){for(var d,m,u=0,f=c.length;u<f;u++)if(node=c[u],1==node.t){d=G.call(g,node.l);for(var e=0,h=node.a&&node.a.length||0;e<h;e++)m=node.a[e],H.call(d,m.n,m.v);node.c&&a(d,node.c);t.call(b,d)}else 3==node.t&&t.call(b,I.call(g,node.v))}var b=J.call(k,'[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"css/gbIrBv.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Magic Actions"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/home64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/opt64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/rate64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/contact64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');p=
v&&53<z?v.call(g.body,{mode:"closed"}):g.body;var c=K.call(g);a(c,b);t.call(p,c)}function L(){M.call(N(".b0"));A.call(p,"click",function(a){var b=a.target;if(b=b.className||b.parentElement&&b.parentElement.className||""){if("b0"===b){var c=99;var d=104}else"b1"===b?(c=300,d=200):"b2"===b?(c=101,d=0):"b3"===b&&(c=303,d=104);O.call(l,P.call(k,{id:7,p:c,f:d}));Q.call(a);R.call(a)}},!0)}function N(a){return v&&53<z?S.call(p,a):T.call(g,a)}function a(){}var O=l.sendMessage,U=l.getURL,B=String.prototype,
q=Storage.prototype,V=Navigator.prototype,W=XMLHttpRequest.prototype,w=DocumentFragment.prototype,d=Document.prototype,C=DOMImplementation.prototype,x=EventTarget.prototype,e=Event.prototype,f=Node.prototype,b=Element.prototype,y=HTMLElement.prototype,G=d.createElement,A=x.addEventListener,K=d.createDocumentFragment,H=b.setAttribute,S=w.querySelector,T=d.querySelector,M=y.focus,t=f.appendChild,I=d.createTextNode,Q=e.preventDefault,R=e.stopPropagation,X=B.slice,D=B.indexOf,v=b.attachShadow||void 0;
try{var r=Object.getOwnPropertyDescriptor(Function.prototype,"call");r&&(r.configurable=!1,r.writable=!1,Object.defineProperty(Function.prototype,"call",r))}catch(m){}q.getItem=a;q.setItem=a;q.removeItem=a;q.clear=a;V.sendBeacon=a;W.open=a;w.querySelector=a;w.querySelectorAll=a;d.createDocumentFragment=a;d.createTextNode=a;d.createElement=a;d.createElementNS=a;d.evaluate=a;d.createEvent=a;d.createCDATASection=a;d.execCommand=a;d.querySelector=a;d.querySelectorAll=a;d.write=a;d.writeln=a;C.createHTMLDocument=
a;C.createDocument=a;x.addEventListener=a;x.removeEventListener=a;e.preventDefault=a;e.stopPropagation=a;e.stopImmediatePropagation=a;f.appendChild=a;f.cloneNode=a;f.getRootNode=a;f.removeChild=a;f.replaceChild=a;f.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;
b.removeAttributeNS=a;b.removeAttributeNode=a;b.replaceWith=a;b.insertAdjacentElement=a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;y.focus=a;y.click=a;var P=k.stringify,J=k.parse,Y=c.parseInt,E=h.userAgent,z=function(){var a=D.call(E,"Chrome/");return-1<a?Y.call(c,X.call(E,a+7)):0}();h=U.call(l,"reNxBtB.html");var p;0!==D.call(c.location.href,h)&&(c.location.href=h);A.call(c,"DOMContentLoaded",function(){F();L()},!0)})(window,document,navigator,JSON,chrome.runtime);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(c){}try{Object.defineProperty(window,"localStorage",_vd)}catch(c){}try{Object.defineProperty(window,"navigator",_vd)}catch(c){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(c){}try{Object.defineProperty(window,"JSON",_vd)}catch(c){}
try{Object.defineProperty(window,"fetch",_vd)}catch(c){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(c){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(c){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(c){};
