// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(f,B,da,S,T,z,U){function V(){F.call(z,C.call(f,{id:0}),W)}function W(h){if(h){var c=h.url;0!=string_indexOf.call(c,"https://www.mycinema.pro/")&&0!=string_indexOf.call(c,ea)&&(B.location.href="about:blank");b=h.opt}(h=u)||(h=B.body,h=attachShadowProto&&53<X?attachShadowProto.call(h,{mode:"closed"}):h);u=h;h=createDocumentFragment.call(B);c=k("ul");c.id="opt";w&&(c.className="localPage",B.body.classList.remove("shadow"));appendChild.call(h,c);var e=u,a=k("link");a.rel="stylesheet";a.type=
"text/css";a.href="css/sNgb.css";appendChild.call(e,a);l(c,"mwvc",d("o8"),b.mwvc,0,0,w?0:{id:7,p:305,f:0});l(c,"mwvcm",d("o82"),b.mwvcm,1,!b.mwvc);l(c,"mwvct",d("o83"),b.mwvct,1,!b.mwvc);l(c,"mwvcr",d("o41"),b.mwvcr,1,!b.mwvc);e="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ");a=k("li");var q=k("label");a.className="sub";setAttribute.call(a,"disabled",!b.mwvc);a.id="color";q.textContent=d("o9");appendChild.call(a,q);for(var t=0,r=e.length;t<
r;t++){var g=e[t];q=k("button");q.id=g;q.style.backgroundColor=g;b.color==g&&(q.className="sel");appendChild.call(a,q);addEventListener.call(q,"click",fa,!1)}appendChild.call(c,a);e=k("li");a=k("label");e.id="mwvci";e.className="sub";setAttribute.call(e,"disabled",!b.mwvci);a.textContent=d("o23");appendChild.call(e,a);p(e,"vc0",d("o85"),0==b.mwvci,G);p(e,"vc1",d("o24"),1==b.mwvci,G);p(e,"vc2",d("o25"),2==b.mwvci,G);p(e,"vc3",d("o26"),3==b.mwvci,G);appendChild.call(c,e);e=d("o27");a=b.gap;q=!b.mwvc;
g=k("li");t=k("label");r=k("input");t.textContent=e;setAttribute.call(t,"for","gap");r.type="range";r.min=1;r.max=25;r.step=1;r.value=a;r.id="gap";r.title="Range: 1-25";appendChild.call(g,t);appendChild.call(g,r);t=k("span");t.textContent=a;appendChild.call(g,t);g.className="sub";setAttribute.call(g,"disabled",q);appendChild.call(c,g);addEventListener.call(r,"change",ha,!1);l(c,"hq",d("o90"),b.hq,0,0,w?0:{id:7,p:306,f:0});e=k("li");e.id="hqi";e.className="sub";setAttribute.call(e,"disabled",!b.hq);
p(e,"highres",d("o91"),"highres"==b.hqi,v);p(e,"hd2880",d("o92"),"hd2880"==b.hqi,v);p(e,"hd2160",d("o93"),"hd2160"==b.hqi,v);p(e,"hd1440",d("o94"),"hd1440"==b.hqi,v);p(e,"hd1080",d("o95"),"hd1080"==b.hqi,v);p(e,"hd720",d("o96"),"hd720"==b.hqi,v);p(e,"large",d("o97"),"large"==b.hqi,v);p(e,"medium",d("o98"),"medium"==b.hqi,v);p(e,"small",d("o99"),"small"==b.hqi,v);p(e,"tiny",d("o100"),"tiny"==b.hqi,v);appendChild.call(c,e);l(c,"mrl",d("o44"),b.mrl);l(c,"wide",d("o28"),b.wide);l(c,"ww",d("o80"),b.ww);
l(c,"cin",d("o29"),b.cin,0,0,w?0:{id:7,p:302,f:0});e=k("li");a=k("label");e.id="cini";e.className="sub";setAttribute.call(e,"disabled",!b.cin);a.textContent=d("o32");appendChild.call(e,a);p(e,"ca0",d("o33"),0==b.cini,K);p(e,"ca1",d("o34"),1==b.cini,K);p(e,"ca2",d("o35"),2==b.cini,K);appendChild.call(c,e);l(c,"cina",d("o30"),b.cina,1,!b.cin);l(c,"cinf",d("o31"),b.cinf,1,!b.cin);l(c,"cinl",d("o65"),b.cinl,1,!b.cin);l(c,"pause",d("o17"),b.pause);l(c,"plist",d("o19"),b.plist,1,!b.pause);l(c,"buf",d("o18"),
b.buf);l(c,"buf1",d("o63"),b.buf1,1,!b.buf);l(c,"loop",d("o40"),b.loop);l(c,"c0",d("o70"),b.c0,0,0,w?0:{id:7,p:307,f:0});L(c,["c1",d("o71"),b.c1,"c4",d("o86"),b.c4],!b.c0);l(c,"anns",d("o42"),b.anns);l(c,"f0",d("o43"),b.f0);l(c,"h0",d("o50"),b.h0);L(c,["h7",d("o56"),b.h7,"h1",d("o51"),b.h1,"h2",d("o52"),b.h2,"h3",d("o53"),b.h3,"h4",d("o54"),b.h4],!b.h0);L(c,["h5",d("o55"),b.h5,"h6",d("o64"),b.h6,"h8",d("o57"),b.h8],!b.h0);l(c,"a0",d("o60"),b.a0,0,0,w?0:{id:7,p:304,f:0});l(c,"a4",d("o81"),b.a4,1,!b.a0);
l(c,"a1",d("o61"),b.a1,1,!b.a0);l(c,"a2",d("o62"),b.a2,1,!b.a0);l(c,"a3",d("o84"),b.a3,1,!b.a0);l(c,"a5",d("o20"),b.a5,1,!b.a0);e=k("li");a=k("a");e.className="opt";a.textContent="Export Options …";a.className="bttn";addEventListener.call(a,"click",ia,!1);appendChild.call(e,a);a=k("a");a.textContent="Import Options …";a.className="bttn";addEventListener.call(a,"click",ja,!1);appendChild.call(e,a);appendChild.call(c,e);appendChild.call(u,h);x("#f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";
h=k("sup");h.textContent=d("m4");h.style.color="red";h.style.verticalAlign="top";appendChild.call(x("#mrl").nextElementSibling,h);x("#mrl").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";if(M){var m=ka.call(M,"sv")||null;m&&localStorage_removeItem.call(M,"sv")}w||f.top.postMessage(la(C.call(f,{t:+new Date,i:700,ver:b.ver,sv:m})),"https://www.mycinema.pro")}function D(b,a,e){F.call(z,C.call(f,{id:4,name:b,value:a,ctx:e}))}
function fa(a){x("#"+b.color).className="";b.color=this.id;this.className="sel";D("color",b.color)}function G(a){x("#vc"+b.mwvci).checked=!1;b.mwvci=E.call(f,this.id.charAt(2));this.checked=!0;D("mwvci",b.mwvci)}function K(a){x("#ca"+b.cini).checked=!1;b.cini=E.call(f,this.id.charAt(2));this.checked=!0;D("cini",b.cini)}function v(a){x("#"+b.hqi).checked=!1;b.hqi=this.id;this.checked=!0;D("hqi",b.hqi)}function Y(a){a=this.id;b[a]=this.checked?!0:!1;D(a,this.checked?!0:!1,"a0"==a||"a3"==a?!0:!1);a=
this.parentElement;if("opt"==a.className)for(a=a.nextElementSibling;a&&("sub"==a.className||"sub multi"==a.className);)setAttribute.call(a,"disabled",!this.checked),a=a.nextElementSibling}function ma(a){b[a.id]=E.call(f,a.value);D(a.id,E.call(f,a.value))}function ha(a){H&&(na.call(f,H),H=null);this.nextElementSibling.textContent=this.value;H=Z.call(f,ma,500,this)}function p(a,b,e,d,f){var c=k("label"),h=k("input");h.type="radio";h.id=b;d&&(h.checked=!0);appendChild.call(a,h);c.textContent=e;setAttribute.call(c,
"for",b);appendChild.call(a,c);addEventListener.call(h,"click",f,!1)}function l(a,b,e,d,g,t,r){var c=k("li"),h=k("label"),q=k("input");h.textContent=e;setAttribute.call(h,"for",b);q.type="checkbox";q.id=b;q.checked=d;appendChild.call(c,q);appendChild.call(c,h);g?(c.className="sub",setAttribute.call(c,"disabled",t)):c.className="opt";r&&(b=k("span"),b.textContent="?",b.title="Learn more about this feature …",b.className="help",Object.defineProperty(b,"mafy",{value:r,writable:!1,configurable:!1,enumerable:!1}),
appendChild.call(c,b),addEventListener.call(b,"click",function(a){F.call(z,C.call(f,this.mafy))},!1));appendChild.call(a,c);addEventListener.call(q,"click",Y,!1)}function L(a,b,e){for(var c=k("li"),d,h,f=0,g=b.length;f<g;f+=3)d=k("label"),h=k("input"),d.textContent=b[f+1],setAttribute.call(d,"for",b[f]),h.type="checkbox",h.id=b[f],h.checked=b[f+2],appendChild.call(c,h),appendChild.call(c,d),addEventListener.call(h,"click",Y,!1);c.className="sub multi";setAttribute.call(c,"disabled",e);appendChild.call(a,
c)}function ia(){var a=C.call(f,b);if(Blob)var c=new Blob([a],{type:"application/json;charset=UTF-8"});else BlobBuilder&&(c=new BlobBuilder,c.append(a),c=c.getBlob("application/json;charset=UTF-8"));oa(c,"MagicActions-Options.json")}function ja(){pa(1E5,function(a){try{a=qa.call(f,a)}catch(ya){return}var c=b.ver,e;for(e in a)void 0!=b[e]&&(b[e]=a[e]);b.ver=c;for(F.call(z,C.call(f,{id:3,opt:b}));u.firstElementChild;)removeChild.call(u,u.firstElementChild);W()})}function pa(a,b){var c=x("#openAs");
c&&removeChild.call(u,c);c=k("input");c.id="openAs";c.style.display="none";c.type="file";appendChild.call(u,c);addEventListener.call(c,"change",function(c){if((c=c.target.files)&&1==c.length&&c[0].size<a){var d=new FileReader;d.onload=function(a){b(a.target.result)};d.readAsText(c[0])}else showMsg("m12",1E3)},!1);el_click.call(c)}function oa(a,b){var c=k("a");c.href=ra(a);setAttribute.call(c,"download",b);el_click.call(c);Z.call(f,function(){sa(c.href)},2E3)}function ta(a){ua("HEAD","https://www.mycinema.pro/",
0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function ua(a,b,d,f,g){var c={code:0},e=new T;xhr_open.call(e,a,b,!0);f&&(e.responseType=f);e.onload=function(a){c.code=this.status||0;c.data=this.response;g(c)};e.onerror=function(){g(c)};e.onabort=function(){g(c)};try{xhr_send.call(e,d)}catch(za){g(c)}}function la(a){for(var b=[],d=[3,0,0,-3],f,h=0,g=a.length;h<g;h++)f=d[h%4],h+f<g?array_push.call(b,string_charCodeAt.call(a,h+f)):array_push.call(b,string_charCodeAt.call(a,h));return b}
function x(a){return attachShadowProto&&53<X?shadow_querySelector.call(u,a):querySelector.call(B,a)}function k(a){return createElement.call(B,a)}function d(a){return va.call(U,a)}function a(){}var F=z.sendMessage,wa=z.getURL,va=U.getMessage,N=String.prototype,aa=Array.prototype,A=Storage.prototype,xa=Navigator.prototype,O=T.prototype,P=DocumentFragment.prototype,m=Document.prototype,ba=DOMImplementation.prototype,Q=EventTarget.prototype,I=Event.prototype,y=Node.prototype,g=Element.prototype,R=HTMLElement.prototype;
HTMLMediaElement_prototype=HTMLMediaElement.prototype;var ka=A.getItem;localStorage_setItem=A.setItem;localStorage_removeItem=A.removeItem;createElement=m.createElement;addEventListener=Q.addEventListener;createDocumentFragment=m.createDocumentFragment;setAttribute=g.setAttribute;appendChild=y.appendChild;removeChild=y.removeChild;createTextNode=m.createTextNode;stopPropagation=I.stopPropagation;shadow_querySelector=P.querySelector;querySelector=m.querySelector;array_push=aa.push;array_join=aa.join;
string_slice=N.slice;string_charCodeAt=N.charCodeAt;string_indexOf=N.indexOf;el_click=R.click;xhr_open=O.open;xhr_send=O.send;attachShadowProto=g.attachShadow||void 0;try{var J=Object.getOwnPropertyDescriptor(Function.prototype,"call");J&&(J.configurable=!1,J.writable=!1,Object.defineProperty(Function.prototype,"call",J))}catch(h){}A.getItem=a;A.setItem=a;A.removeItem=a;A.clear=a;xa.sendBeacon=a;O.open=a;P.querySelector=a;P.querySelectorAll=a;m.createDocumentFragment=a;m.createTextNode=a;m.createElement=
a;m.createElementNS=a;m.evaluate=a;m.createEvent=a;m.createCDATASection=a;m.execCommand=a;m.querySelector=a;m.querySelectorAll=a;m.write=a;m.writeln=a;ba.createHTMLDocument=a;ba.createDocument=a;Q.addEventListener=a;Q.removeEventListener=a;I.preventDefault=a;I.stopPropagation=a;I.stopImmediatePropagation=a;y.appendChild=a;y.cloneNode=a;y.getRootNode=a;y.removeChild=a;y.replaceChild=a;y.insertBefore=a;g.attachShadow=a;g.createShadowRoot=a;g.getElementsByClassName=a;g.getElementsByTagName=a;g.getElementsByTagNameNS=
a;g.append=a;g.remove=a;g.before=a;g.after=a;g.prepend=a;g.querySelector=a;g.querySelectorAll=a;g.requestPointerLock=a;g.setAttribute=a;g.removeAttribute=a;g.removeAttributeNS=a;g.removeAttributeNode=a;g.replaceWith=a;g.insertAdjacentElement=a;g.insertAdjacentText=a;g.insertAdjacentHTML=a;R.focus=a;R.click=a;HTMLMediaElement_prototype.play=a;var C=S.stringify,qa=S.parse,Z=f.setTimeout,na=f.clearTimeout,E=f.parseInt,sa=f.URL.revokeObjectURL,ra=f.URL.createObjectURL,ca=da.userAgent,X=function(){var a=
string_indexOf.call(ca,"Chrome/");return-1<a?E.call(f,string_slice.call(ca,a+7)):0}(),ea=wa.call(z,"NMFk.html"),w=f.self==f.top,u,b,H;try{var M=f.localStorage}catch(h){}addEventListener.call(f,"DOMContentLoaded",function(){w?ta(function(a){a?f.location.href="https://www.mycinema.pro/options.html":V()}):V()},!0)})(window,document,navigator,JSON,XMLHttpRequest,chrome.runtime,chrome.i18n);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(f){}try{Object.defineProperty(window,"localStorage",_vd)}catch(f){}try{Object.defineProperty(window,"navigator",_vd)}catch(f){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(f){}try{Object.defineProperty(window,"JSON",_vd)}catch(f){}
try{Object.defineProperty(window,"fetch",_vd)}catch(f){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(f){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(f){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(f){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(f){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(f){};
